services:
  products-import-php-fpm:
    container_name: php-fpm
    build:
      context: ./.docker
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - './app:/var/www/app:rw'
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - products-import-network
  products-import-nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8096:80"
    volumes:
      - "$PWD/app:/var/www/app:rw"
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - products-import-php-fpm
    networks:
      - products-import-network
    restart: unless-stopped
  products-import-mysql:
    container_name: mysql
    image: mysql:8.4.3
    volumes:
      - "./.data/db/mysql8:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: importTest
    ports:
      - "33076:3306"
    networks:
      - products-import-network

networks:
  products-import-network:
    driver: bridge
